blueprint:
  name: " - Daily On|Off Schedule (Persistent)"
  description: For domains supporting On/Off state. Input_datetimes needed to set and maintain On/Off.
  domain: automation
  input:
    on_time:
      name: On Time
      selector:
        entity:
          domain: input_datetime
    off_time:
      name: Off Time
      selector:
        entity:
          domain: input_datetime
    target_entity:
      name: Target Entity
      selector:
        entity:
    blocker_boolean:
      name: Boolean
      description: Boolean to Enable/Disable Schedule
      default: input_boolean.none
      selector:
        entity:
          domain: input_boolean

variables:
  on_time: !input 'on_time'
  off_time: !input 'off_time'
  target_entity: !input 'target_entity'
  target_domain: "{{ states[target_entity].domain }}"
  blocker_bool: !input 'blocker_boolean'

trigger:
  - platform: time
    id: on_time
    at: !input on_time
  - platform: time
    id: off_time
    at: !input off_time
  - platform: homeassistant
    id: ha_start
    event: start
  - platform: state
    id: persist_trigs
    entity_id:
      - sensor.time               # sensor.time evaluates every minute
      - !input 'blocker_boolean'  # Toggling blocker
      - !input 'on_time'          # Changed on_time helper
      - !input 'off_time'         # Changed off_time helper
      - !input 'target_entity'    # Target changes state

condition:
# Proceed if no blocker is set, or if blocker is 'on'
  - condition: template
    value_template: "{{ blocker_bool == 'input_boolean.none' or states[blocker_bool].state == 'on' }}"

action:
# If triggered time = on time
  - choose:
    - conditions:
      - condition: trigger
        id: on_time
      sequence:
      - service: >
          {{ target_domain + ".turn_on" }}
        data: {}
        entity_id: !input 'target_entity'

# If triggered time = off time
  - choose:
    - conditions:
      - condition: trigger
        id: off_time
      sequence:
      - service: >
          {{ target_domain + ".turn_off" }}
        data: {}
        entity_id: !input 'target_entity'

# If HA restarted, entity state changes, or any setting changes
  - choose:
      - conditions:
          - condition: trigger
            id: persist_trigs
        sequence:
          - choose:
              - conditions:
                  - condition: time
                    after: !input on_time
                    before: !input off_time
                sequence:
                  - service: >
                      {{ target_domain + ".turn_on" }}
                    data: {}
                    entity_id: !input 'target_entity'
            default:
              - service: >
                  {{ target_domain + ".turn_off" }}
                data: {}
                entity_id: !input 'target_entity'
mode: restart