blueprint:
  name: " - Daily On|Off Schedule"
  description: For domains supporting On/Off state. Input_datetimes needed to trigger On/Off.
  domain: automation
  input:
    on_time:
      name: On Time
      selector:
        entity:
          domain: input_datetime
    off_time:
      name: Off Time
      selector:
        entity:
          domain: input_datetime
    target_entity:
      name: Target Entity
      selector:
        entity:
    blocker_boolean:
      name: Boolean
      description: Boolean to Enable/Disable Schedule
      default: input_boolean.none
      selector:
        entity:
          domain: input_boolean

variables:
  on_time: !input 'on_time'
  off_time: !input 'off_time'
  target_entity: !input 'target_entity'
  target_domain: "{{ states[target_entity].domain }}"
  blocker_boolean: !input 'blocker_boolean'

trigger:
  - platform: time
    id: on_time
    at: !input on_time
  - platform: time
    id: off_time
    at: !input off_time
  - platform: state
    id: blocker_toggle
    entity_id:
      - !input 'blocker_boolean'  # Toggling blocker


condition:
  - condition: template
    value_template: "{{ blocker_boolean == 'input_boolean.none' or states[blocker_boolean].state == 'on' }}"


action:
  - choose:
      - conditions:
          - condition: trigger
            id: on_time
        sequence:
        - service: >
            {{ target_domain + ".turn_on" }}
          data: {}
          entity_id: !input 'target_entity'
  - choose:
      - conditions:
          - condition: trigger
            id: off_time
        sequence:
        - service: >
            {{ target_domain + ".turn_off" }}
          data: {}
          entity_id: !input 'target_entity'
  - choose:
      - conditions:
          - condition: trigger
            id: blocker_toggle
        sequence:
          - choose:
              - conditions:
                  - condition: time
                    after: !input on_time
                    before: !input off_time
                sequence:
                - service: >
                    {{ target_domain + ".turn_on" }}
                  data: {}
                  entity_id: !input 'target_entity'
            default:
            - service: >
                {{ target_domain + ".turn_off" }}
              data: {}
              entity_id: !input 'target_entity'

mode: restart